const express = require("express");
const mongoose = require("mongoose");
const cors = require("cors");
const bodyParser = require("body-parser");
const PizZip = require("pizzip");
const Docxtemplater = require("docxtemplater");
const fs = require("fs");
const path = require("path");
const PDFDocument = require("pdfkit");


const app = express();

// Middleware
app.use(cors());
app.use(bodyParser.json());

// Connect to MongoDB
mongoose
  .connect(
    "mongodb+srv://2004vimal:zaq1%40wsx@cluster0.kfsrfxi.mongodb.net/SiddhaShivalayas",
    {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    }
  )
  .then(() => console.log("MongoDB connected"))
  .catch((err) => console.error("MongoDB connection error:", err));

// Routes
const stockRoutes = require("./routes/stock");
const patientRoutes = require("./routes/patient");

app.use("/stocks", stockRoutes);
app.use("/patients", patientRoutes);

app.get("/", (req, res) => {
  res.json("Hello World");
});

// Cache the template content to avoid reading it multiple times
const templatePath = path.resolve(__dirname, "bill_template.docx");
let content;
try {
  content = fs.readFileSync(templatePath, "binary");
} catch (err) {
  console.error("Error loading template file:", err);
  process.exit(1); // Exit the process if template loading fails
}

// Optimized Bill Generation Endpoint
app.post("/generate-bill", (req, res) => {
  const {
    id,
    name,
    phone,
    address,
    treatmentOrMedicine,
    date,
    items,
    discount,
  } = req.body;

  // Validation: Ensure all required fields are provided
  if (
    !id ||
    !name ||
    !phone ||
    !address ||
    !date ||
    !Array.isArray(items) ||
    items.length === 0
  ) {
    return res.status(400).send("Error: Missing required fields.");
  }

  // Validate items structure
  for (let item of items) {
    if (!item.description || !item.price || !item.quantity || !item.GST) {
      return res
        .status(400)
        .send(
          "Error: Each item must have description, price, quantity, and GST."
        );
    }
    if (isNaN(item.price) || isNaN(item.quantity) || isNaN(item.GST)) {
      return res
        .status(400)
        .send("Error: Price, quantity, and GST must be valid numbers.");
    }
  }

  // Ensure discount is a valid number (if undefined, default to 0)
  const discountValue = isNaN(discount) ? 0 : parseFloat(discount);

  // Process items and calculate totals
  const itemTotals = items.map((item) => {
    const itemPrice = parseFloat(item.price);
    const itemQuantity = parseFloat(item.quantity);
    const gstRate = parseFloat(item.GST) / 100;

    const baseTotal = itemPrice * itemQuantity;
    const gstAmount = baseTotal * gstRate;
    const finalAmount = baseTotal + gstAmount;

    return {
      ...item,
      baseTotal: baseTotal.toFixed(2),
      gstAmount: gstAmount.toFixed(2),
      finalAmount: finalAmount.toFixed(2),
    };
  });

  // Calculate subtotal, total GST, and final total
  const subtotal = itemTotals.reduce(
    (sum, item) => sum + parseFloat(item.baseTotal),
    0
  );
  const totalGST = itemTotals.reduce(
    (sum, item) => sum + parseFloat(item.gstAmount),
    0
  );
  const finalTotal = (subtotal + totalGST - discountValue).toFixed(2);

  // Generate PDF
  const doc = new PDFDocument();
  let buffers = [];
  doc.on("data", (chunk) => buffers.push(chunk));
  doc.on("end", () => {
    const pdfData = Buffer.concat(buffers);
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=generated-bill-${id}.pdf`
    );
    res.setHeader("Content-Type", "application/pdf");
    res.send(pdfData);
  });

  // Add content to PDF
  doc.fontSize(20).text("Bill Details", { align: "center" }).moveDown();

  // Add patient details
  doc
    .fontSize(12)
    .text(`Patient ID: ${id}`)
    .text(`Name: ${name}`)
    .text(`Phone: ${phone}`)
    .text(`Address: ${address}`)
    .text(`Treatment/Medicine: ${treatmentOrMedicine || "N/A"}`)
    .text(`Date: ${date}`)
    .moveDown();

  // Add table headers
  doc
    .fontSize(12)
    .text("Items:", { underline: true })
    .moveDown()
    .text(
      `Description | HSN | GST | Quantity | Price | Base Total | GST Amount | Final Amount`
    )
    .moveDown();

  // Add items
  itemTotals.forEach((item) => {
    doc.text(
      `${item.description} | ${item.HSN} | ${item.GST}% | ${item.quantity} | ₹${item.price} | ₹${item.baseTotal} | ₹${item.gstAmount} | ₹${item.finalAmount}`
    );
  });

  doc
    .moveDown()
    .text(`Subtotal: ₹${subtotal.toFixed(2)}`)
    .text(`Total GST: ₹${totalGST.toFixed(2)}`)
    .text(`Discount: ₹${discountValue.toFixed(2)}`)
    .text(`Final Total: ₹${finalTotal}`)
    .moveDown();

  // Footer
  doc.fontSize(10).text("Generated by Siddha Shivalayas", {
    align: "center",
  });

  // Finalize the PDF
  doc.end();
});

// Start server
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
